#debug: true

logging:
  level:
    root: WARN
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none