#debug: true

logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
#  jpa:
#    hibernate:
#       ddl-auto: none #this will turn off Hibernate's auto-configuration/population of the DB, will fall back to Spring Boot looking for schema.sql & data.sql

#####    Application-specific Configuration    #########

taco:
  orders:
    pageSize: 25